version: 0.2

phases:
  build:
    commands:
      - chmod +x scripts/ApplicationStart.sh
      - chmod +x gradlew
      - ./gradlew build -x test
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - appspec.yml
    - build/libs/*.jar
    - logs/*
    - scripts/*
    
